# Generated by Django 4.2.6 on 2023-10-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location_type", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("faction_type", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                (
                    "affiliated_locations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="affiliated_factions",
                        to="populator.location",
                    ),
                ),
                (
                    "base_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_factions",
                        to="populator.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                ("profession", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                ("stats", models.CharField(max_length=100)),
                ("abilities", models.CharField(max_length=500)),
                (
                    "faction",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="populator.faction"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="populator.location",
                    ),
                ),
            ],
        ),
    ]
