# Generated by Django 5.0.1 on 2024-01-09 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='location',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='affiliated_locations',
        ),
        migrations.AddField(
            model_name='character',
            name='frequent_locations',
            field=models.ManyToManyField(blank=True, related_name='frequent_characters', to='populator.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='populator.location'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faction',
            name='base_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_location__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_factions', to='populator.location'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(),
        ),
    ]
