# Generated by Django 5.0.1 on 2024-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("populator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="image_hs",
            field=models.ImageField(
                blank=True, null=True, upload_to="character_images/headshots"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="image_iso",
            field=models.ImageField(
                blank=True, null=True, upload_to="character_images/isometric"
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="faction_images/"),
        ),
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="location_images/"
            ),
        ),
    ]
