# Generated by Django 5.0.1 on 2026-07-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0003_remove_location_party_size_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.CharField(default='NG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='rank_tier',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('officer', 'Officer'), ('member', 'Member'), ('mob', 'Mob')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='rank_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faction',
            name='alignment',
            field=models.CharField(default='NG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='hierarchy',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faction',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
