# Generated by Django 5.0.1 on 2024-03-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0003_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='frequent_locations',
        ),
        migrations.RemoveField(
            model_name='character',
            name='role',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='base_location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent_location',
        ),
        migrations.AddField(
            model_name='character',
            name='actions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='lead',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faction',
            name='location',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='populator.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='party_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='party_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='character',
            name='faction',
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='populator.faction'),
            preserve_default=False,
        ),
    ]
