# Generated by Django 5.0.1 on 2026-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0004_character_alignment_character_rank_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(max_length=50),
        ),
    ]
