# Generated by Django 5.0.1 on 2026-07-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0005_location_summary_alter_character_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='lead',
        ),
    ]
