# Generated by Django 5.0.1 on 2026-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0006_remove_character_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='instances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faction',
            name='is_catchall',
            field=models.BooleanField(default=False),
        ),
    ]
